name: ci-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nightwatch:
    name: ${{ matrix.browser }}
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm install
      - run: npm run test:${{ matrix.browser }}
        env:
          STANDARD: ${{ secrets.STANDARD }}
          PASSWORD: ${{ secrets.PASSWORD }}
